# **Assignment - Numpy**

# **Theoretical Questions:**

# **Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**Ans:** NumPy, short for Numerical Python, is a powerful library in Python that provides extensive support for numerical operations and scientific computing. Its primary purpose is to facilitate the handling and manipulation of large, multi-dimensional arrays and matrices, alongside a collection of mathematical functions to operate on these arrays efficiently.

### **Purpose of NumPy :**

  1. **Array Representation:** NumPy introduces the ndarray object, which is a fast, flexible container for large datasets in Python. This allows users to work with data in multi-dimensional arrays more intuitively.
  2. **Performance:** NumPy is optimized for performance, leveraging contiguous memory allocation and efficient looping mechanisms. Operations on NumPy arrays can be significantly faster than those on standard Python lists, especially for large datasets.
  3. **Mathematical Functions:** It provides a rich set of mathematical functions to perform operations such as linear algebra, statistical analysis, Fourier transforms, and more, making it a core tool for scientific computing.

  4. **Interoperability:** NumPy serves as a foundation for many other libraries in the scientific computing ecosystem, such as SciPy, Pandas, and Matplotlib, enhancing Python's capabilities for data analysis and visualization.

### **Advantages of NumPy :**

1. **Efficient Array Operations:**

  *  NumPy provides the ndarray object, which is a highly optimized array structure that supports fast element-wise operations.

  * Unlike Python lists, NumPy arrays are contiguous in memory, allowing for efficient storage and processing.

  * Vectorized operations (such as addition, multiplication, etc.) can be performed directly on arrays, removing the need for explicit loops and making code both faster and more concise.

2. **Speed and Performance:**

  * NumPy is implemented in C, making array operations significantly faster than using pure Python, especially for large datasets.

  * Operations in NumPy are optimized and often take advantage of parallelism, enabling faster computations than standard Python code.

  * Broadcasting, a feature of NumPy, allows for the efficient execution of operations on arrays of different shapes and sizes, further enhancing performance without needing complex code.

3. **Mathematical and Statistical Functions:**

  * NumPy includes a vast range of mathematical and statistical functions, like trigonometric, logarithmic, exponential, linear algebraic, and statistical functions.

  * This makes it a complete toolkit for numerical data analysis, as users don’t need to implement these calculations manually.

4. **Support for Multi-Dimensional Arrays:**

  * NumPy arrays (ndarrays) can have multiple dimensions, making it possible to represent and operate on matrices, tensors, and other high-dimensional data structures used in advanced scientific computing.

  * Functions like reshaping, slicing, and indexing allow for flexible manipulation of array data, making it easy to work with complex data formats.

5. **Interoperability with Other Libraries:**

  * NumPy is designed to integrate seamlessly with other Python libraries used in data analysis, machine learning, and scientific computing.

  * Libraries like pandas, SciPy, and TensorFlow are built on top of or compatible with NumPy arrays, allowing for smooth transitions between different types of analyses and operations.

6. **Memory Efficiency:**

  * NumPy arrays are more memory-efficient than Python lists, as they store elements of the same data type in contiguous memory blocks.

  * This is particularly useful when dealing with large datasets, as it reduces the memory overhead and speeds up processing.

7. **Data Type Flexibility:**

  * NumPy arrays support a wide range of data types (integers, floats, complex numbers, etc.), as well as custom data types, which can be useful for scientific applications with strict data requirements.

  * You can also perform type casting and specify data types at array creation, which enhances control over data representation and processing.

### **Enhancements to Python's Numerical Capabilities :**

* **Vectorization:** Eliminates the need for explicit loops in many operations, leading to faster execution and clearer, more concise code.

* **Broadcasting:** Automatically expands arrays of different shapes for element-wise operations, making complex mathematical operations simpler.

* **Integration:** Provides a common data structure that most scientific and data libraries support, making it easier to integrate and scale projects.

Overall, NumPy enhances Python’s ability to handle and process numerical data efficiently, allowing scientists, analysts, and developers to conduct complex computations and data analysis with ease. This efficiency is essential for fields that rely on heavy computation, such as physics, finance, data science, and machine learning.

# **Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**Ans:** **The np.mean()** and **np.average()** functions in NumPy are both used to calculate the average of elements in an array, but they have some key differences in functionality and flexibility.

### **np.mean()**

* **Purpose:** Computes the arithmetic mean (average) of the elements along a specified axis.
* **Syntax:** np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
* **Default Behavior:** By default, it calculates the mean of all elements in the input array.
* **Parameters:**
  
  ▪ **a:** Input array.

  ▪ **axis:** Axis or axes along which to compute the mean. Default is None, meaning the mean is computed over the entire array.
  
  ▪ **dtype:** Data type to use for the calculation.

  ▪ **out:** A location into which the result is stored (optional).

  ▪ **keepdims:** If True, the reduced axes are left in the result as dimensions with size one.

### **np.average()**

* **Purpose:** Computes the weighted average of the elements in an array.
* **Syntax:** np.average(a, axis=None, weights=None, returned=False)
* **Default Behavior:** Computes the mean of all elements if no weights are provided, similar to np.mean().
* **Parameters:**

  ▪ **a:** Input array.
  
  ▪ **axis:** Axis or axes along which to compute the average.
  
  ▪ **weights:** An array of weights, same shape as a. If provided, the average is weighted accordingly.
  
  ▪ **returned:** If True, returns a tuple of the average and the sum of the weights.


## **Key Differences :**

### **Weighted Average**
  * **np.mean():** Not supported
  * **np.average():** Supported with a weights parameter

### **Default Behavior**
  * **np.mean():** Calculates simple mean
  * **np.average():** Calculates weighted mean if weights provided; otherwise, simple mean

### **Output**
  * **np.mean():** Returns a float (or array if axis is specified)
  * **np.average():** Returns a float (or array if axis is specified); returns a tuple if weights and axis are provided

### **Performance**
  * **np.mean():** Slightly faster for simple mean
  * **np.average():** Slightly slower when using weights

## **3. When to Use np.mean() vs. np.average()**

  * Use **np.mean()** when you just need the simple arithmetic mean of an array, as it is straightforward and slightly faster.

  * Use **np.average()** when you need a weighted average. Weighted averages are useful in situations where some elements in the dataset carry more importance or weight than others, such as:

    * **Grading:** When calculating a final grade based on assignments with different weights.

    * **Financial Calculations:** When averaging stock prices or portfolio returns based on holdings’ proportions.
    
    * **Scientific Measurements:** When averaging measurements that have different degrees of reliability.






In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

# Using np.mean()
mean_value = np.mean(data)
print("Mean:", mean_value)  # Output: Mean: 3.0

# Using np.average() without weights
average_value = np.average(data)
print("Average:", average_value)  # Output: Average: 3.0

# Using np.average() with weights
weights = np.array([1, 1, 1, 2, 2])  # Giving more weight to the last two elements
weighted_average = np.average(data, weights=weights)
print("Weighted Average:", weighted_average)  # Output: Weighted Average: 3.6

Mean: 3.0
Average: 3.0
Weighted Average: 3.4285714285714284


# **Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

**Ans:** In NumPy, reversing an array along different axes can be achieved with slicing or specific functions. Here’s a look at both approaches for 1D and 2D arrays:

### **1. Reversing a 1D Array**

To reverse a 1D array, you can use slicing. The syntax array[::-1] reverses the array.

**Example:**



In [1]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_1d)


Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


### **2. Reversing a 2D Array**

In a 2D array, you can reverse along different axes:

* **Reverse along the first axis (rows):** This flips the rows.
* **Reverse along the second axis (columns):** This flips the columns.
* **Reverse along both axes:** This reverses both rows and columns.

**Example:**


In [2]:
# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = arr_2d[::-1, :]

# Reverse along the second axis (columns)
reversed_columns = arr_2d[:, ::-1]

# Reverse along both axes (rows and columns)
reversed_both = arr_2d[::-1, ::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed along rows:\n", reversed_rows)
print("Reversed along columns:\n", reversed_columns)
print("Reversed along both axes:\n", reversed_both)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### **Explanation**

* `arr[::-1]` reverses the elements along a given axis.
* `arr[::-1, :]` reverses rows in a 2D array.
* `arr[:, ::-1]` reverses columns in a 2D array.
* `arr[::-1, ::-1]` reverses both rows and columns, essentially rotating the 2D array 180 degrees.



# **Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

**Ans:** In NumPy, you can determine the data type of elements in an array using the .dtype attribute. This attribute returns the data type of the array's elements, which can be useful for understanding how the data is stored and manipulated.

### **Determining the Data Type**

Here’s how you can check the data type of a NumPy array:



In [3]:
import numpy as np

# Creating an array with integer data type
arr = np.array([1, 2, 3])

# Checking the data type
print("Data type of array elements:", arr.dtype)


Data type of array elements: int64


### **Importance of Data Types in Memory Management and Performance**

1. ### **Memory Management:**

   ◾ **Efficient Storage:** Different data types consume different amounts of memory. For example, an int32 takes 4 bytes, while an int64 takes 8 bytes. Using the appropriate data type can significantly reduce memory usage, especially for large datasets.
  
  ◾ **Data Type Casting:** You can explicitly specify the data type when creating an array (e.g., np.array([1, 2, 3], dtype=np.float32)) to optimize memory usage. This can be crucial in environments with limited resources.

2. ### **Performance:**

  ◾ **Speed of Operations:** Operations on arrays of smaller data types (e.g., float32 vs. float64) can be faster because they require less memory bandwidth and processing power. This can lead to better performance in computations.

  ◾ **Vectorized Operations:** NumPy’s performance benefits from using contiguous memory blocks for uniform data types. This allows for optimized, vectorized operations, which are much faster than looping through individual elements in pure Python.

3. ### **Data Integrity:**

  ◾ **Type Consistency:** Ensuring that all elements in an array are of the same type prevents errors that might arise from mixing data types (e.g., integer and string) and provides clearer semantics for numerical operations.
  
  ◾ **Control Over Numerical Precision:** The choice of data type allows control over precision and range. For example, using float16 can save memory but may introduce rounding errors that would not occur with float64.


### **Example of Data Type Impact on Memory**


In [4]:
# Creating arrays with different data types
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

print("Memory used by int32 array:", arr_int32.nbytes, "bytes")
print("Memory used by float64 array:", arr_float64.nbytes, "bytes")


Memory used by int32 array: 12 bytes
Memory used by float64 array: 24 bytes


This illustrates how selecting the right data type can impact both memory usage and processing efficiency.








# **Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans:**  In NumPy, ndarrays (n-dimensional arrays) are the core data structure used for storing and manipulating numerical data. They are highly efficient and optimized for performance in scientific computing and data analysis. Here’s a detailed explanation of ndarrays and their key features, along with a comparison to standard Python lists.

### **Key Features of ndarrays**

**1. Homogeneity:**
* All elements in an `ndarray` are of the same data type, such as `int32`, `float64`, or `bool`. This homogeneity enables efficient storage and fast computation.

**2. N-dimensional:**
* `ndarray` can have any number of dimensions (1D, 2D, 3D, etc.), making it suitable for representing various data structures like vectors, matrices, and tensors.

**3. Shape and Size:**
* The `.shape` attribute provides the dimensions of the array (e.g., `(3, 3)` for a 3x3 array), while `.size` gives the total number of elements in the array.

**4. Efficient Memory Usage:**
* `ndarray` is implemented as a contiguous block of memory, which allows NumPy to perform memory-intensive operations more efficiently than standard Python lists. This contiguous layout enables better caching and faster access during computations.

**5. Vectorized Operations:**
* NumPy arrays support vectorized operations, meaning you can apply operations across entire arrays without explicit loops. This feature enables high-performance computations since operations are optimized and parallelized under the hood.

**6. Broadcasting:**
* NumPy allows arrays of different shapes to be combined in arithmetic operations using broadcasting. This enables, for example, adding a 1D array to a 2D array without needing to reshape it.

**7. Comprehensive Mathematical Functions:**
* NumPy provides a broad range of functions, including trigonometric, statistical, and linear algebra functions, that operate directly on `ndarray` objects, making it ideal for numerical and scientific computing.


### **Differences Between ndarray and Standard Python Lists**


| Feature                      | NumPy Ndarrays                        | Python Lists                   |
|------------------------------|---------------------------------------|--------------------------------|
| **Data Type**                | Homogeneous (single data type)	               | Heterogeneous (mixed data types)
    |
| **Memory Efficiency**            | Fixed-size, contiguous memory block	           | Dynamic, less memory-efficient
|
| **Performance**              | Faster, optimized for vectorized ops	        | Slower for large-scale operations
  |
| **Dimensionality**               | N-dimensional (1D, 2D, 3D, etc.)	         | Primarily 1D (lists of lists for 2D)
         |
| **Vectorized Ops**           | Supported, allows element-wise ops	               | Not natively supported
      |
| **Broadcasting**       | Supported	       | Not supported
     |
| **Mathematical Functions**         | Extensive NumPy library	  | Limited to basic operations
    |


### **Example Comparison**


In [5]:
import numpy as np

# NumPy ndarray
arr = np.array([1, 2, 3, 4, 5])

# Standard Python list
lst = [1, 2, 3, 4, 5]

# Element-wise multiplication (NumPy)
print("NumPy ndarray multiplied by 2:", arr * 2)

# Element-wise multiplication (Python list)
print("Python list multiplied by 2:", [x * 2 for x in lst])


NumPy ndarray multiplied by 2: [ 2  4  6  8 10]
Python list multiplied by 2: [2, 4, 6, 8, 10]


In this example, **arr * 2**  performs element-wise multiplication on the entire NumPy array directly, whereas with a Python list, we have to loop through each element to achieve the same result. This illustrates how **ndarray** provides more efficient and concise operations than standard Python lists.








# **Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**Ans:** The performance benefits of NumPy arrays over Python lists for large-scale numerical operations are significant and stem from several key factors. Here’s a detailed analysis of why NumPy arrays are generally preferred for numerical computations in Python:

### **1. Memory Efficiency and Contiguity**

* **Fixed Data Type:** NumPy arrays store elements of a single, fixed data type, allowing them to use a contiguous block of memory. This contiguity enables efficient memory access patterns, reducing memory overhead and improving CPU cache utilization.

* **Compact Storage:** Unlike Python lists, which store each element as an individual Python object with its own overhead, NumPy arrays use a simpler, lower-overhead representation. This compact storage further minimizes memory usage, especially with large datasets.

### **2. Vectorized Operations**

* NumPy supports vectorized operations, meaning that mathematical operations can be applied to entire arrays at once without explicit loops. In contrast, Python lists require looping through each element, which adds significant overhead in the Python interpreter.

* Vectorized operations leverage underlying C and Fortran code, which is highly optimized for performance, bypassing the slower, interpreted Python layer. This allows NumPy to perform large-scale computations many times faster than pure Python.

In [6]:
import numpy as np

# Large NumPy array and Python list
array = np.arange(1_000_000)
list_data = list(range(1_000_000))

# Vectorized multiplication with NumPy
array_result = array * 2

# Equivalent multiplication with Python list (requires a loop)
list_result = [x * 2 for x in list_data]


In this example, **array * 2** is optimized and executed in one step internally, whereas the Python list requires a loop, making the NumPy approach faster.

### **3. Broadcasting Capabilities**

* Broadcasting in NumPy allows operations on arrays of different shapes and sizes without explicitly reshaping them, saving computational time and simplifying code. For example, adding a scalar to a multi-dimensional array happens in one efficient operation, whereas in Python, manual looping would be required.

* This ability to “broadcast” operations across dimensions reduces the need for complex code, and the underlying C implementation optimizes the memory usage and speed of these operations.





In [7]:
# Broadcasting a scalar to a large 2D array
large_array = np.ones((1000, 1000))
result = large_array + 5


Here, 5 is added to every element of `large_array` without explicitly creating a new array of the same shape, achieving the operation in a single, efficient step.

### **4. Numerical Libraries and Optimized Algorithms**

* NumPy integrates with highly optimized numerical libraries, such as BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package), which are specifically designed for high-performance mathematical operations.

* This integration enables NumPy to efficiently handle complex operations, such as matrix multiplication, solving linear equations, and performing singular value decomposition (SVD), which would be impractical with Python lists due to speed and memory constraints.

### **5. Parallel Processing and Multi-threading**

* Many NumPy operations, particularly linear algebra operations, are parallelized and can take advantage of multi-core CPUs. This parallelization can lead to significant speed-ups on large datasets, where operations are spread across multiple CPU cores.

* Python lists don’t natively support parallelized or multi-threaded operations, meaning they rely entirely on single-threaded processing, which is much slower for large-scale data processing.

### **6. Benchmark Comparison Example**

Let's compare the performance of a simple operation—adding two large arrays/lists element-wise—using NumPy arrays vs. Python lists:




In [8]:
import numpy as np
import time

# Creating large NumPy array and Python list
size = 10_000_000
array1 = np.arange(size)
array2 = np.arange(size)
list1 = list(range(size))
list2 = list(range(size))

# Timing NumPy array addition
start = time.time()
result_array = array1 + array2
end = time.time()
print("NumPy array addition time:", end - start)

# Timing Python list addition
start = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)


NumPy array addition time: 0.12495255470275879
Python list addition time: 1.825040340423584


In this example, NumPy completes the operation in a fraction of the time compared to Python lists. This difference becomes even more pronounced as the data size increases.



# **Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**Ans:** In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. These functions are particularly useful when you want to combine multiple arrays along specific axes.

### **1. vstack()**
  * **Purpose:** Stacks arrays in sequence vertically (row-wise). It is equivalent to concatenating along the first axis (axis=0).

  * **Input Requirement:** The input arrays must have the same shape along all but the first axis.


**Example of vstack():**




In [9]:
import numpy as np

# Define two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically stack the arrays
vstack_result = np.vstack((arr1, arr2))
print("vstack result:\n", vstack_result)


vstack result:
 [[1 2 3]
 [4 5 6]]


In this case, vstack() combines the arrays as rows in a new 2D array.

**Example with 2D Arrays:**


In [10]:
# Define two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Vertically stack the 2D arrays
vstack_result = np.vstack((arr1, arr2))
print("vstack result:\n", vstack_result)


vstack result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Here, vstack() appends arr2 as additional rows to arr1, resulting in a 4x3 array.

### **2. hstack()**

  * **Purpose:** Stacks arrays in sequence horizontally (column-wise). It is equivalent to concatenating along the second axis (axis=1).

  * **Input Requirement:** The input arrays must have the same shape along all but the second axis.

**Example of hstack():**




In [11]:
# Define two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stack the arrays
hstack_result = np.hstack((arr1, arr2))
print("hstack result:", hstack_result)


hstack result: [1 2 3 4 5 6]


In this example, `hstack()` concatenates the arrays as a single 1D array by appending elements of `arr2` to `arr1`.

**Example with 2D Arrays:**




In [12]:
# Define two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontally stack the 2D arrays
hstack_result = np.hstack((arr1, arr2))
print("hstack result:\n", hstack_result)



hstack result:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Here, hstack() appends arr2 as additional columns to arr1, resulting in a 2x6 array.

### **Key Differences Between vstack() and hstack()**

▶ **Axis of Stacking:**

  * **vstack()** stacks vertically along rows (axis 0).
  * **hstack()** stacks horizontally along columns (axis 1).

▶ **Dimensional Requirements:**

  * For vstack(), the arrays must have the same number of columns.
  * For hstack(), the arrays must have the same number of rows.

▶ **Shape of Result:**

  * vstack() increases the row count.
  * hstack() increases the column count.

# **Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

**Ans:**  In NumPy, the **fliplr()** and **flipud()** functions are used to flip (reverse) the elements of arrays along specific axes. Here's a detailed explanation of the differences between these two methods, along with their effects on various array dimensions.

* **fliplr():** Flips an array left to right (horizontally).
* **flipud():** Flips an array upside down (vertically).

### **Key Differences :**

| Function   | Direction of Flip	        | Affected Axis	        | Usage Example        |
|------------|---------------------|-----------------------------|-----------------------------|
| `fliplr()` | Left to Right	 | Columns	            | Used for 2D arrays
 |
| `flipud()` | Up to Down	      | Rows               | Used for 2D arrays |

### **1. fliplr(): Flip Left to Right**

* **Purpose:** Flips an array from left to right (horizontally). It is specifically used for 2D arrays.
* **Effect:** For a 2D array, fliplr() reverses the order of columns.

**Example of vstack() with 2D Array:**


In [13]:
import numpy as np

# Define a 2D array
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Flip the array left to right
fliplr_result = np.fliplr(arr)
print("Original array:\n", arr)
print("After fliplr:\n", fliplr_result)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After fliplr:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


### **2. flipud(): Flip Up to Down**

* **Purpose:** Flips an array from up to down (vertically). It is also primarily used for 2D arrays.
* **Effect:** For a 2D array, flipud() reverses the order of rows.

**Example of flipud() with 2D Array:**






In [14]:
# Flip the array upside down
flipud_result = np.flipud(arr)
print("Original array:\n", arr)
print("After flipud:\n", flipud_result)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After flipud:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


### **Effects on Various Array Dimensions**

**A. 1D Arrays:**

* Both fliplr() and flipud() have the same effect on 1D arrays, which is to reverse the order of elements.

**Example :**



In [15]:
arr_1d = np.array([1, 2, 3, 4, 5])
fliplr_1d = np.fliplr(arr_1d.reshape(1, -1))  # Must reshape for fliplr
flipud_1d = np.flipud(arr_1d.reshape(1, -1))  # Must reshape for flipud
print("1D array after fliplr:", fliplr_1d)
print("1D array after flipud:", flipud_1d)


1D array after fliplr: [[5 4 3 2 1]]
1D array after flipud: [[1 2 3 4 5]]


**B. 2D Arrays:**

* **fliplr():** Reverses columns.

* **flipud():** Reverses rows.


**C. 3D Arrays:**

For 3D arrays, **fliplr()** operates along the last axis (columns), while **flipud()** operates along the first axis (slices of the 3D array).

**Example :**





In [16]:
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

fliplr_3d = np.fliplr(arr_3d)
flipud_3d = np.flipud(arr_3d)

print("Original 3D array:\n", arr_3d)
print("After fliplr on 3D array:\n", fliplr_3d)
print("After flipud on 3D array:\n", flipud_3d)


Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
After fliplr on 3D array:
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
After flipud on 3D array:
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


# **Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans:** he array_split() function in NumPy is a versatile method used to split an array into multiple sub-arrays. It is particularly useful when you want to divide data for analysis or processing without requiring equal-sized splits.

### **Functionality of array_split()**


In [ ]:
numpy.array_split(array, indices_or_sections, axis=0)


▶  **Parameters:**

* **array:** The input array to be split.
* **indices_or_sections:** This can be either an integer or a sequence of indices. If it’s an integer, it specifies the number of equal sections to split the array into. If it’s a sequence, it specifies the exact indices at which to split.
* **axis:** The axis along which to split the array. The default is 0, meaning that the split occurs along the first dimension.

▶ **Returns:** A list of sub-arrays created from the split.

### **Example of array_split()**

**Equal Splits**

When the number of sections is evenly divisible by the length of the array, `array_split()` creates equal-sized sub-arrays.





In [21]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
split_equal = np.array_split(array_1d, 3)
print("Equal splits:", split_equal)


Equal splits: [array([1, 2]), array([3, 4]), array([5, 6])]


**Uneven Splits**

If the array cannot be split evenly, `array_split()` will distribute the elements as evenly as possible. This means some sub-arrays may contain one more element than others.



In [22]:
# Split into 4 parts
split_uneven = np.array_split(array_1d, 4)
print("Uneven splits:", split_uneven)

Uneven splits: [array([1, 2]), array([3, 4]), array([5]), array([6])]


In this example, because the array has 6 elements and is being split into 4 parts, the resulting sub-arrays are distributed such that two sub-arrays contain 2 elements, and the other two contain 1 element each.

### **Handling of Uneven Splits**

When the array cannot be split evenly (i.e., the array length is not divisible by the number of sections), array_split() distributes the remainder to the initial sections, making some sub-arrays slightly larger than others.

For example, if you have an array of 10 elements and you want to split it into 3 sections, the split will result in sub-arrays with lengths [4, 3, 3] rather than requiring an even division (which would be impossible here). The first few sub-arrays are given an extra element to handle the remainder.

### **Examples**

**Example 1:** Basic Usage with Integer **`indices_or_sections`**




In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 3 sections
split_result = np.array_split(arr, 3)
print("Result of array_split with 3 sections:", split_result)


Result of array_split with 3 sections: [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


Here, array_split() divides the array into 3 sections with lengths [4, 3, 3], assigning an extra element to the first section to account for the uneven split.


**Example 2:** Specifying `indices_or_sections` as a List of Indices

You can also provide a list of indices to array_split() to specify custom split points.




In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split at specified indices
split_result = np.array_split(arr, [3, 5, 8])
print("Result of array_split with specified indices:", split_result)


Result of array_split with specified indices: [array([1, 2, 3]), array([4, 5]), array([6, 7, 8]), array([ 9, 10])]


**In this case:**

* The array is split at indices [3, 5, 8], so the result contains four sub-arrays.
* The sections are [1, 2, 3], [4, 5], [6, 7, 8], and [9, 10].

**Example 3:** Splitting Along a Specified Axis

For multi-dimensional arrays, you can use the axis parameter to specify the axis along which the array is split.



In [25]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Split along columns (axis=1) into 3 parts
split_result = np.array_split(arr_2d, 3, axis=1)
print("Result of array_split along columns:", split_result)


Result of array_split along columns: [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


**Here:**

* The array is split along the columns (axis=1) into 3 parts.
* The first section has 2 columns, and the remaining sections have 1 column each, demonstrating how array_split() handles uneven splits along different axes.

# **Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

**Ans:** In NumPy, vectorization and broadcasting are two powerful concepts that significantly enhance the efficiency of array operations. They allow for high-performance numerical computations without the need for explicit loops, making code more concise and easier to read.

### **1. Vectorization**
**Definition:** Vectorization refers to the process of replacing explicit loops in code with array operations that operate on entire arrays (or large chunks of them) at once. This takes advantage of NumPy's underlying implementation in C and Fortran, which is optimized for performance.

### **Benefits of Vectorization:**
* **Performance:** Vectorized operations are executed at a lower level, leading to faster execution compared to loops written in Python.

* **Code Clarity:** Code becomes cleaner and more readable. Instead of writing loops, you can express operations succinctly.

**Example of Vectorization:**

Suppose you want to multiply each element in an array by 2. Here’s how you can do it with and without vectorization:



In [7]:
import numpy as np

# Define a large array
arr = np.array([1, 2, 3, 4, 5])

# Using vectorized operation
result_vectorized = arr * 2

# Using a loop (non-vectorized)
result_loop = [x * 2 for x in arr]

print("Vectorized result:", result_vectorized)
print("Loop result:", result_loop)


Vectorized result: [ 2  4  6  8 10]
Loop result: [2, 4, 6, 8, 10]


The vectorized approach **(arr * 2)** is not only faster but also more concise. For large arrays, this speed difference becomes significant.

### **2. Broadcasting**

**Definition:** Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes. When performing arithmetic operations on arrays, NumPy automatically expands the smaller array across the larger array so that they have compatible shapes.

**Rules for Broadcasting:**

1. **If the arrays have a different number of dimensions**, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes are the same.
2. **If the sizes of the dimensions are different**, broadcasting occurs when one of the dimensions is 1. The array with size 1 in that dimension is expanded to match the size of the other array.

### **Benefits of Broadcasting:**

* **Efficiency:** Reduces memory usage and computational overhead since it avoids the creation of large temporary arrays.
* **Simplicity:** Enables operations between arrays of different shapes without needing to manually replicate data.

**Example of Broadcasting:**

Consider adding a 1D array to each row of a 2D array:



In [8]:
# Define a 2D array and a 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_1d = np.array([10, 20, 30])

# Broadcasting the 1D array to match the 2D array for element-wise addition
result = arr_2d + arr_1d
print("Broadcasting result:\n", result)


Broadcasting result:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


Here:

The 1D array `[10, 20, 30]` is broadcasted to match the shape of the 2D array `arr_2d`.
Each row of `arr_2d` receives an element-wise addition with `[10, 20, 30]`, which would require loops if done manually.

### **Contribution to Efficient Array Operations**

### **1. Reduced Loop Overheads**
* Both vectorization and broadcasting eliminate the need for explicit Python loops, reducing the computational overhead.

* Operations are performed in compiled code (C or Fortran), leveraging low-level optimizations for speed.

### **2. Memory Optimization**

* Broadcasting minimizes memory usage by avoiding unnecessary data duplication. Instead of creating large, repeated arrays, broadcasting performs operations as if the smaller array were expanded.

* This memory efficiency is crucial for handling large datasets or high-dimensional data, allowing complex operations to be performed without significant memory overhead.

**3. Enhanced Readability and Code Simplicity**

* Vectorized and broadcasted operations make code cleaner and easier to read, as they often condense complex operations into single expressions.

* This simplicity allows for more maintainable code and reduces the chance of errors that can arise from manual looping.

# **Practical Questions :-**

# **Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

**Ans:**

Here is the 3x3 NumPy array with random integers between 1 and 100:




In [15]:
import numpy as np

# Define the array correctly
original_array = np.array([[9, 45, 26],
                          [32, 55, 37],
                          [45, 8, 20]])

print("Original Array:\n", original_array)

Original Array:
 [[ 9 45 26]
 [32 55 37]
 [45  8 20]]


**After interchanging its rows and columns (transposing):**



In [17]:
# Define the array correctly
original_array = np.array([[9, 45, 26],
                          [32, 55, 37],
                          [45, 8, 20]])

# Calculate the transpose and print
transposed_array = original_array.T  # Calculate the transpose using .T attribute
print("Transposed Array (Interchanged Rows and Columns):\n", transposed_array)

Transposed Array (Interchanged Rows and Columns):
 [[ 9 32 45]
 [45 55  8]
 [26 37 20]]


# **Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

**Ans:**


**Original 1D Array (10 elements):**



In [26]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
array_1d



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Reshaped to 2x5 Array:**



In [29]:
# Reshape the array into 2x5
array_2x5 = array_1d.reshape(2, 5)
array_2x5


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Reshaped to 5x2 Array:**



In [30]:
# Reshape the array into 5x2
array_5x2 = array_1d.reshape(5, 2)
array_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# **Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

**Ans:** **4x4 Array:**

In [33]:
import numpy as np

random_array = np.round(np.random.rand(4, 4), 2)
random_array

array([[0.16, 0.28, 0.31, 0.34],
       [0.13, 0.95, 0.44, 0.06],
       [0.73, 0.73, 0.21, 0.99],
       [0.34, 0.37, 0.07, 0.43]])

**6x6 Array with Border of Zeros:**

In [34]:
bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)
bordered_array

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.16, 0.28, 0.31, 0.34, 0.  ],
       [0.  , 0.13, 0.95, 0.44, 0.06, 0.  ],
       [0.  , 0.73, 0.73, 0.21, 0.99, 0.  ],
       [0.  , 0.34, 0.37, 0.07, 0.43, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

# **Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

**Ans:**

In [35]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 65, 5)

# Print the result
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


# **Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

**Ans:**


In [36]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(arr)           # Uppercase
lower_case = np.char.lower(arr)           # Lowercase
title_case = np.char.title(arr)           # Title Case
capitalize_case = np.char.capitalize(arr) # Capitalize

# Print the results
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalize:", capitalize_case)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


# **Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

**Ans:**


In [38]:
import numpy as np

# Create a NumPy array of words
words = np.array(['computer', 'science', 'engineering'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the result
print(spaced_words)

['c o m p u t e r' 's c i e n c e' 'e n g i n e e r i n g']


# **Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

**Ans:**

In [39]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# **Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

**Ans:**

In [40]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


# **Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

**Ans:**


In [41]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)

Random Integers: [ 37 179  38 189 369 732 366 813 833 683 598 640 782 182  22 885 535 993
 613 192 266 614 588 964 294 829 346 634 766 421 839 198 463 249 392 618
 182 198 354 666 693 554 583  34  98  14 951 727 490 821 837  31 400 693
 244 312 659 641 142 207 594 194 974 178  18 908  15 605 800 903 188 176
 790 270  51 164 708 113 183 662 280 891 590 394 839 500 973 779 140 999
 796 783 748 927 202 505 369 316 835 562]
Prime Numbers: [37, 179, 683, 613, 829, 421, 839, 463, 727, 821, 31, 659, 641, 113, 839]


# **Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

**Ans:**

In [42]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.uniform(32, 90, 30)  # Fahrenheit

# Reshape array to 5 weeks, with the last week having fewer days if needed
# The total number of elements in the reshaped array must match the original array
num_weeks = 5  # Change this to the desired number of weeks
weekly_temperatures = daily_temperatures.reshape(num_weeks, -1) #-1 is inferred from the length of the array and remaining dimension which is 5
# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display daily temperatures and weekly averages
print("Daily Temperatures:")
print(daily_temperatures)

print("\nWeekly Temperatures:")
print(weekly_temperatures)

print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages):
    print(f"Week {i + 1}: {avg:.2f}°F")

Daily Temperatures:
[63.83118323 73.48098325 66.96027581 63.60322461 56.57197836 69.46185856
 57.38005825 83.72283405 87.89244011 54.23960809 77.92005221 62.67590535
 64.94658454 85.68460502 36.12009138 37.05349938 33.17266705 80.29195104
 77.13309156 82.4607046  88.75986385 78.35119672 58.76580301 77.27069222
 38.8599167  69.11541924 40.31449067 86.79079719 62.26720266 56.05039252]

Weekly Temperatures:
[[63.83118323 73.48098325 66.96027581 63.60322461 56.57197836 69.46185856]
 [57.38005825 83.72283405 87.89244011 54.23960809 77.92005221 62.67590535]
 [64.94658454 85.68460502 36.12009138 37.05349938 33.17266705 80.29195104]
 [77.13309156 82.4607046  88.75986385 78.35119672 58.76580301 77.27069222]
 [38.8599167  69.11541924 40.31449067 86.79079719 62.26720266 56.05039252]]

Weekly Averages:
Week 1: 65.65°F
Week 2: 70.64°F
Week 3: 56.21°F
Week 4: 77.12°F
Week 5: 58.90°F
